In [ ]:
# !pip install datasets transformers scikit-learn evaluate torchinfo tqdm accelerate -U

# Access Token 생성
- 학습된 모델을 Huggingface hub에 올리기 위해서는 access token이 필요하다.

![huggingface_create_apikey.png](figures/huggingface_accesstoken.png)
![huggingface_create_apikey.png](figures/huggingface_accesstoken2.png)

- 1. 로그인 -> 2. Profile -> 3. Access Tokens 선택
- 생성할 때 `write` 권한을 선택한다.

# HuggingFace Datasets 패키지

- HuggingFace Datasets는 머신러닝 모델 학습에 필요한 대규모 데이터셋을 효율적으로 로드, 전처리, 변환, 스트리밍할 수 있도록 지원하는 라이브러리이다.
- HuggingFace Hub에 등록된 다양한 데이터셋을 동일한 인터페이스로 접근할 수 있다.
- 설치

  - `pip install datasets`
- 공식 문서

  - [Dataset Hub: https://huggingface.co/datasets](https://huggingface.co/datasets)
  - [https://github.com/huggingface/datasets](https://github.com/huggingface/datasets)
  - [https://huggingface.co/docs/datasets/index](https://huggingface.co/docs/datasets/index)
## Dataset과 DatasetDict

### Dataset

- 하나의 데이터셋을 테이블 형태(행 = 샘플, 열 = Feature)로 저장하는 구조.
- 텍스트, 이미지, 오디오, 멀티모달 데이터 지원.
- PyTorch, TensorFlow 학습 파이프라인과 연동 가능.
- Lazy Loading 및 Streaming을 통해 대규모 데이터도 메모리 효율적으로 처리.

### DatasetDict

- 여러 Dataset을 key-value 형태로 묶어 관리한다.

  - 예: `{"train": Dataset, "validation": Dataset, "test": Dataset}`
- key를 통해 데이터셋에 접근.

## DatasetDict / Dataset 로딩
- `datasets.load_dataset()` 이용
  
### Hub 데이터 로딩
- Huggingface hub에 등록된 Dataset의 id를 전달하면  다운로드 후 로딩한다.

```python
from datasets import load_dataset
dataset_dict = load_dataset("imdb")
```
![img](figures/huggingface_dataset.png)

### 로컬 파일 로딩

```python
dataset_dict = load_dataset(
    "csv",
    data_files={
        "train": "data/train.csv",
        "validation": "data/valid.csv",
        "test": "data/test.csv"
    }
)
```

### 다양한 소스에서 Dataset 생성

```python
from datasets import Dataset

Dataset.from_pandas(df) # DataFrame을 Dataset으로 로딩
Dataset.from_dict({"text": [...], "label": [...]}) # 딕셔너리를 Dataset으로 로딩
Dataset.from_csv("path.csv") # 경로의 csv파일을 Dataset으로 로딩
```

## Dataset 주요 기능

### 데이터 접근(조회)

- 인덱싱으로 샘플 조회: `dataset[0]`
- 슬라이싱: `dataset[:10]`

### 전처리 관련 메소드

#### map()

데이터셋의 모든 데이터(또는 지정한 batch)에 변환 함수를 적용한다.

```python
dataset.map(
    function,                    # 각 샘플/배치에 적용할 함수
    batched=False,               # True: 배치 단위 입력
    batch_size=1000,             # batched=True일 때 배치사이즈. 기본값: 1000
    remove_columns=None,         # 변환 후 제거할 컬럼 리스트
    num_proc=None,               # 병렬 처리 프로세스 개수
)
```

##### map에 전달하는 함수(function)의 입력(parameter)/출력(return) 형태
- parameter: dict - Dataset의 데이터를 dict(컬럼명, 값) 로 받는다. batched=False일 경우 개별 값, True일 경우 값은 iterable
- return: dict - 처리한 결과. dict(컬럼명, 처리값) 지정한 컬럼에 처리한 값을 저장한다. 컬럼명이 **기존 컬럼이면 덮어쓰고, 없는 컬럼이면 추가**한다. `remove_columns=컬럼명` 옵션을 지정하면 처리가 끝난 뒤 지정한 컬럼을 제거할  수 있다.
- `batched=False` (기본값) 일 때

  - 함수 입력: dict (하나의 row)
  - 함수 반환: dict (추가될 컬럼 포함)

    ```python
    def add_length(example):
        example["text_len"] = len(example["text"])
        return example

    dataset = dataset.map(add_length)
    ```

- `batched=True` 일때 (배치단위 입력)

  - 함수 입력: dict (여러 row의 컬럼이 리스트로 묶여 들어옴)
  - 함수 반환: dict (리스트 형태 유지)

    ```python
    def add_length_batch(batch):
        return {"text_len": [len(t) for t in batch["text"]]}

    dataset = dataset.map(add_length_batch, batched=True)
    ```

#### filter()

조건 함수를 적용하여 True를 반환하는 row만 남긴다.

```python
dataset.filter(
    function,           # 조건 함수
    batched=False,      # 배치 처리 여부
    num_proc=None,      # 병렬 처리
    desc=None
)
```

##### filter()에 전달하는 함수의 입력(parameter)/출력(return) 형태
- parameter: dict - Dataset의 데이터를 dict(컬럼명, 값) 로 받는다. batched=False일 경우 개별 값, True일 경우 값은 iterable
- return: bool -  Dataset에 남길지 말지 조건
- `batched=False`: 한 줄씩 조건 적용

  ```python
  dataset = dataset.filter(lambda x: x["label"] == 1)
  ```

- `batched=True`: 배치 활용

  ```python
  def filter_positive(batch):
      return [label == 1 for label in batch["label"]]

  dataset = dataset.filter(filter_positive, batched=True)
  ```

## 기타 유용 메소드

- **컬럼 삭제**
  - `dataset = dataset.remove_columns(["column_name"])`
- **컬럼 이름 변경**
  - `dataset = dataset.rename_column("orig", "new")`
- **데이터 분할**
  - `dataset.train_test_split(test_size=0.2)`

- **저장**

  ```python
  dataset.save_to_disk("path/")
  dataset = datasets.load_from_disk("path/")
  ```

- 모델학습 프레임워크용 포맷 변환
  - 기본적으로 Dataset의 데이터들은 list 로 저장됨.
  - pytorch나 tensorflow에서 사용할 수있도록 format을 변환. (값을 제공할 때 지정한 타입으로 변환해서 반환한다.)

    ```python
    dataset.set_format(type="torch") # numpy, torch, tensorflow, python
    ```

- Streaming 로딩
    - Huggingface Hub의 데이터셋이 너무 클 경우(수백 GB) 필요한 데이터만 순차적으로 가져와 로딩하여 처리할 수있다.
      ```python
      ds_stream = load_dataset("c4", split="train", streaming=True)

      for sample in ds_stream:
        sample 로 사용
      ```

# 유튜브 댓글 감정 분석 데이터셋
- https://huggingface.co/datasets/LLM-SocialMedia/Korean-YouTube-Comment-Sentiment-Dataset
- `LLM-SocialMedia/Korean-YouTube-Comment-Sentiment-Dataset`

In [ ]:
from datasets import load_dataset

# Huggingface dataset hub의 Dataset 로딩 -> id
dataset_dict = load_dataset("LLM-SocialMedia/Korean-YouTube-Comment-Sentiment-Dataset")

In [ ]:
type(dataset_dict)

datasets.dataset_dict.DatasetDict

In [ ]:
dataset_dict

DatasetDict({
    train: Dataset({
        features: ['cid', 'text', 'time', 'author', 'channel', 'votes', 'replies', 'heart', 'reply', 'time_parsed', 'source_video_id', 'source_video_title', 'text_length', 'is_not_spam', 'votes_norm', 'replies_norm', 'heart_norm', '검수_감정'],
        num_rows: 10035
    })
})

In [ ]:
# DatasetDict에서 Dataset 조회
dataset = dataset_dict['train']
dataset

Dataset({
    features: ['cid', 'text', 'time', 'author', 'channel', 'votes', 'replies', 'heart', 'reply', 'time_parsed', 'source_video_id', 'source_video_title', 'text_length', 'is_not_spam', 'votes_norm', 'replies_norm', 'heart_norm', '검수_감정'],
    num_rows: 10035
})

In [ ]:
# Dataset관련 정보 조회
# feature(컬럼) 정보
dataset.features # 컬럼명:컬럼의타입

{'cid': Value('string'),
 'text': Value('string'),
 'time': Value('string'),
 'author': Value('string'),
 'channel': Value('string'),
 'votes': Value('int64'),
 'replies': Value('int64'),
 'heart': Value('bool'),
 'reply': Value('bool'),
 'time_parsed': Value('float64'),
 'source_video_id': Value('string'),
 'source_video_title': Value('string'),
 'text_length': Value('int64'),
 'is_not_spam': Value('bool'),
 'votes_norm': Value('float64'),
 'replies_norm': Value('float64'),
 'heart_norm': Value('int64'),
 '검수_감정': Value('string')}

In [ ]:
# feature 개수 , # 행의 개수 -> 총 데이터수
dataset.num_columns, dataset.num_rows

(18, 10035)

In [ ]:
## 컬럼을 제거(필요없는 컬럼 삭제)
dataset = dataset.remove_columns(['cid', 'time', 'author', 'channel', 'votes', 'replies', 'heart', 'reply', 'time_parsed', 'source_video_id', 'source_video_title', 'text_length', 'is_not_spam', 'votes_norm', 'replies_norm', 'heart_norm'])
dataset

Dataset({
    features: ['text', '검수_감정'],
    num_rows: 10035
})

In [ ]:
## feature(컬럼) 이름 변경. dict로 입력 -{현재이름 : 변경할이름}
dataset = dataset.rename_columns({
    "text":"comment",
    "검수_감정":"labels"
})
dataset

Dataset({
    features: ['comment', 'labels'],
    num_rows: 10035
})

In [ ]:
# feature의 값들 조회 - indexing/slicing
dataset['comment'][0]
dataset['comment'][:5]

['PERSON_002 예쁘고 귀엽다 언제든지 PERSON_001 응원하고 있을게 화이팅!!!!',
 '팬덤이 계속 보길 원하고, 글로벌적 수요가 분명 타레이블보다 높음에도 경영진의 입맛에 맞지 않다는 이유로 공연을 막고, 광고계약을 막아서 수입창출을 막는 것은 부당한 것 맞음. 법이 제대로 해석해내지못한 부분이 분명 있음\n\n법이 불완전한 부분이 있는데, 부당해도 법이 이러니깐 감내해. 너희가 뭔데 나대는데.. 이런식의 비야냥과 무력한 인간들의 조롱조차도 여태해왔던 용기와 에너지로 이겨내요, PERSON_003.\n일일히 댓글달지 못하지만, 마음으로 응원하고 당신들의 목소리에 귀기울이고 이해하고 있는 사람은 그대들이 생각하는 것보다 훨씬 많아요.\n세상을 바꿀지도 모를 그대들을 응원합니다.  \n 마흔의 나이에도 어린 당신들의 용기를 배웁니다.',
 'PERSON_003 데뷔때부터 팬인데 이젠 나도 쉴드못쳐주겟다.. 하니가 국회 갔을때부터 일이 ㅈㄴ 잘못됐어 ㅆ1ㅂ; 그이후로 본인들이 감당 못할말을 계속 해버리니까 이사단이 나지 진짜 개슬프네..PERSON_003',
 '참고로 PERSON_003 탄핵집회를 선결제해줬다 ㅋㅋ',
 '해외인터뷰에 혐한발언은 진짜 미친거아님? 왜 가면갈수록 멍청한 발언만 골라가면서 하냐? 멤버들은 어리니까 그렇다쳐도 케어해주는 부모들은 뭔생각인거지??']

In [ ]:
dataset['labels'][:5]

['긍정', '긍정', '부정', '건너뛰기', '부정']

In [ ]:
# feature의 고유값(unique값) 조회
dataset.unique("labels")

['긍정', '부정', '건너뛰기', '중립', '불명확', '', '긍정정', '중립립']

In [ ]:
# "긍정정" -> "긍정" | "중립립" -> "중립" | "건너뛰기" -> "불명확"(차후에 삭제)
label_map = {
    '긍정정':'긍정',
    '중립립':'중립',
    '건너뛰기':'불명확'
}

def update_labels(row):
    # row: map이 전달할 dataset의 한개 행 값. {"comment":"댓글", "labels":"라벨"}
    # map(batched=True)일 때, {"comment":[배치개수], "labels":[배치개수]}
    label = row['labels']
    # label_map에 있는 것은 바뀌어서, 아닌 것은 원래값 그대로
    new_label = label_map.get(label, label)
    return {'labels' : new_label}   # {"feature이름":처리결과}


dataset = dataset.map(update_labels)  # , batched=True) : 한 번에 여러개씩 처리 (default: 100)
# map(함수): 일괄처리
## 함수(개별행): {처리결과를 저장할 feature의 이름 : 처리 결과}

In [ ]:
dataset.unique("labels")

['긍정', '부정', '불명확', '중립', '']

In [ ]:
# 불명확, '' 인 labels는 제거 -> 행을 제거.
# filter()를 이용해서 labels가 "불명확", ""이 아닌 행들만 남긴다.
## filter(함수) -> dataset의 개별항을 받아서 bool을 반환. 그 행을 True이면 남기고 False이면 사용하지 않는다.

def check_labels(row):
    # filter에 전달할 함수
    # 파라미터: Dataset의 한 행(batched=True이면 여러행).
    #          dict-{컬럼명:값, 컬럼명:값}, batched=True: {컬러명:[배치개수]}
    # return: bool - 그 행을 사용할 지 여부
    flag = row['labels'] != '불명확' and row['labels'] != ''
    return flag

dataset = dataset.filter(check_labels)
# check_labels 함수가 바로 return이 가능한 코드이므로 lambda를 활용해도 괜찮다.
# dataset = dataset.filter(lambda row: row['labels'] != '불명확' and row['labels'] != '')

Filter:   0%|          | 0/10035 [00:00<?, ? examples/s]

In [ ]:
dataset

Dataset({
    features: ['comment', 'labels'],
    num_rows: 5571
})

In [ ]:
dataset.unique('labels')

Flattening the indices:   0%|          | 0/5571 [00:00<?, ? examples/s]

['긍정', '부정', '중립']

## Train/Test set split

In [ ]:
dataset.features
# Value(타입): 행마다 제각각 다른값들을 가진다. (범주형이 아니다.)
# ClassLabel: 범주형 컬럼. - 문자열범주값 - 정수 범주값으로 관리.

{'comment': Value('string'), 'labels': Value('string')}

In [ ]:
# labels의 타입을 ClassLabel로 변환
dataset = dataset.class_encode_column("labels")

In [ ]:
dataset.features

{'comment': Value('string'), 'labels': ClassLabel(names=['긍정', '부정', '중립'])}

In [ ]:
# ClassLabel 타입 feature사용
dataset['labels'].features
dataset['labels'].features.names # class 이름(문자열), index: class id(정수)
dataset['labels'].features.str2int('긍정') # class 이름으로 class id 조회
dataset['labels'].features.int2str(2) # class id로 class 이름을 조회

'중립'

In [ ]:
## 섞고 나서 분할
# 섞기
dataset = dataset.shuffle() # seed=42) seed: random seed값 지정 -> 항상 일정한 순서로 조회.

# 분할
dataset_dict = dataset.train_test_split(
    test_size=0.15, # test set의 비율
    stratify_by_column="labels"
    # 지정한 컬럼의 값들이 비율에 맞게 분할. 지정한 feature는 ClassLabel 타입이어야함.
)

In [ ]:
dataset_dict

DatasetDict({
    train: Dataset({
        features: ['comment', 'labels'],
        num_rows: 4735
    })
    test: Dataset({
        features: ['comment', 'labels'],
        num_rows: 836
    })
})

In [ ]:
train_set = dataset_dict['train']
test_set = dataset_dict['test']

train_set, test_set

(Dataset({
     features: ['comment', 'labels'],
     num_rows: 4735
 }),
 Dataset({
     features: ['comment', 'labels'],
     num_rows: 836
 }))

In [ ]:
# 전처리한 Dataset을 huggingface datahub에 upload
# 1. login -> access token
# 2. upload: dataset/dataset_dict.push_to_hub("계정/dataset_id")

# 로그인
from huggingface_hub import login
from dotenv import load_dotenv
import os

load_dotenv() # .env의 key-value들이 os의 환경변수로 저장
hf_token = os.getenv("HUGGINGFACE_API_KEY")

login(hf_token)

In [ ]:
dataset_dict.push_to_hub("Wjaehyun97/youtube_comment_sentiment_dataset_preprocessing")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/datasets/Wjaehyun97/youtube_comment_sentiment_dataset_preprocessing/commit/eb0772f91660b992ef73cd1fd514292f9075701f', commit_message='Upload dataset', commit_description='', oid='eb0772f91660b992ef73cd1fd514292f9075701f', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/Wjaehyun97/youtube_comment_sentiment_dataset_preprocessing', endpoint='https://huggingface.co', repo_type='dataset', repo_id='Wjaehyun97/youtube_comment_sentiment_dataset_preprocessing'), pr_revision=None, pr_num=None)

In [1]:
# huggingface에 업로드한 데이터셋 load
from datasets import load_dataset
load_dataset_dict= load_dataset("Wjaehyun97/youtube_comment_sentiment_dataset_preprocessing")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/715 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/375k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/64.0k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4735 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/836 [00:00<?, ? examples/s]

In [3]:
load_dataset_dict

DatasetDict({
    train: Dataset({
        features: ['comment', 'labels'],
        num_rows: 4735
    })
    test: Dataset({
        features: ['comment', 'labels'],
        num_rows: 836
    })
})

In [ ]:
##########################
# 로컬 컴퓨터에 저장
##########################
dataset_dict.save_to_disk("data/youtube_comment_dataset") # 저장할 디렉토리 경로

Saving the dataset (0/1 shards):   0%|          | 0/4735 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/836 [00:00<?, ? examples/s]

In [ ]:
# 로컬에서 불러오기
from datasets import load_from_disk
load_dataset_dict2 = load_from_disk("data/youtube_comment_dataset")
load_dataset_dict2

DatasetDict({
    train: Dataset({
        features: ['comment', 'labels'],
        num_rows: 4735
    })
    test: Dataset({
        features: ['comment', 'labels'],
        num_rows: 836
    })
})

In [ ]:
############################
# Dataset을 다른 형식으로 변환

# Dataset을 pandas DataFrame
df_train = dataset_dict['train'].to_pandas()
df_train.head()

                                             comment  labels
0                                     알루미늄 농장도 살려야쥬~       1
1  어떻게 한국 사람 얼굴이 저렇게 입체적이지..배치가 너무 조화롭고 오밀조밀해서 개잘...       0
2  보통 얼굴을 이렇게 적나라하게 조명 아래 클로즈업 하면 "아...여기를 좀 더 키우...       0
3  안락사 합법화 시켜야함. 80세 이상은 모두 안락사 대상.\n더 살고 싶으면 지금 ...       1
4  진짜 그릇도 안되는 애가 100만 유튜브되고 이런게 까발라지니 진짜 웃음벨이네 ㅋㅋ...       1

In [ ]:
# train_set.to_json
train_set.to_dict()

{'comment': ['알루미늄 농장도 살려야쥬~',
  '어떻게 한국 사람 얼굴이 저렇게 입체적이지..배치가 너무 조화롭고 오밀조밀해서 개잘생김 특히 이마에서 코로 내려오는 티존, 코가 하나하나 뜯어보면 진짜 감탄을 안할수가 없다,,거기에 상반되는 여리고 만두같은 성격까지,..,.,,,,본인은 세보이고 싶지만 웅냥냥 말투는 어쩔수없는건갘ㅋㅋ그거마저 귀여운데 이거 설정 과다 아닌가요',
  '보통 얼굴을 이렇게 적나라하게 조명 아래 클로즈업 하면 "아...여기를 좀 더 키우고.. 여기는 좀 짧으면 더 낫겠는데.."라는 단점이 보이기 마련인데.. 정말 완벽하게 잘 갖춰진 얼굴이라 그런 생각이 하나도 안든다.. 정말 혀를 내두르게 만드는 얼굴이구나.. 완벽하다 정말. 진짜.. 잘생겼구나 현진.',
  '안락사 합법화 시켜야함. 80세 이상은 모두 안락사 대상.\n더 살고 싶으면 지금 당장 세금 더 내게해야지 뭐.',
  '진짜 그릇도 안되는 애가 100만 유튜브되고 이런게 까발라지니 진짜 웃음벨이네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '영상 초기에 댓글 훈수 이야기가 나와서 의견 한번 내보면\n보급기 가격은 사실 엔비디아의 MSRP 상술 생색내기를 맞추기 위해 나온 제품이라 5090 정도되면 사실 저가격으로 구하기 어려운 경우가 많습니다. 아마 보면 품절이라서 저 가격으로 구하기 어렵거나 할겁니다. MSRP 맞췄다는 생색내기 제품으로 소량 생산하고 더이상 들여오지 않습니다. 그래서 하급기와 중급기 가격차이가 크게 느껴지지만 사실 실제 구할 수 있는 제품 기준으로 보면 대개 다 가격이 올라갔습니다 ㅎㅎ 그래서 실제 구할 수 있는 제품 중 하급기 기준으로 비교하게 되면 가격 격차가 생각보다 줄어들겁니다. 지금 유통 레벨이 굉장히 복잡해서 딱 얼마 차이다 라고 규정짓기가 어렵고 이제 슬슬 하락기조에 들어섰기 때문에 싯가 정책이 끝난후 다시 고민해보는것도 좋을 것 같습니다.\n그리고 사실 상급기는 갬성과 만족감 원툴이라 가치관이 달라서 가성비로 비교하는게 맞지 않는것 같습니다. 일단 상급기로 갈 수록 데스크 셋업이나 깔맞춤 등의 부가가치가 부여되기 때문에.. 그와 반대로 가성비에 가치관이 있다면 사실 이번 5000번대는 하급기도 온도 제법 괜찮기 때문에 하급기로 가셔도 가성비 측면에서 무난할 것 같습니다.\n\n대체로 등급별로도 가격 차이가 크기 때문에 윗등급 글카에 가까울 수록 그만한 비용을 지출 할 수 있는 사용자 입장에서 상급기 선호 기조가 크고 아랫 등급 글카에 가까울 수록 사용자가 가성비 선호 기조가 크기도 하죠.\n\n마지막으로 이런 토론 컨텐츠 괜찮네요. 잘 봤습니다.',
  '더 내고 못받기',
  '라면조회수 달달했는데 쫙쫙 빨아먹어야지~',
  'ㅋㅋ100만원 마라탕&마라샹궈 해주세여 PERSON_023 치트기!! 중식으로!!!🎉🎉😊',
  '너무 재밌어요!! 다음에는 100만원짜리 국밥(삼계탕)이나 비빔밥해주세요!',
  '진짜 댓글안다는데 이건 말이안되게 못해서 댓글을 달게만드네 진짜 방송잘한다.... ck 탑 감스트밸런스로 한번만 해줘',
  '100만원 마라탕 기원 1일차',
  '개짜증난다(positive) 사귀라고',
  '와 근데 사람들 무섭다 꼬투리 잡으니까 한도 끝도 없이 비난이구나. 상장한 회사가 시골동내바리 구멍가게도 아니고 예전부터 PERSON_006 우리농가 살린다고 자회사 다 국산쓰는게 아니고 조회수 높으니까 우리나라 양파 대파 마늘 제품좋다고 공짜 홍보 해주고 그랬는데. 상장한 대기업이 어떻게 다 국산쓰냐 그럼 가격 비싸다고 안먹을거면서 이분은 사업가임 (음식에대해 지식이 정말 많은) 뭐하나 잡히니까 죽이려고 덤벼드네. 님들 분노는 PERSON_006 아니고 님들이 이렇게 남물어뜯고 힘들게 생활할수 밖에 없게 만든 정치인들한테 더 분노해야지.  지들 먹고살기 힘들다고 더본 회사에 니네가 잘못해서 우리가 먹고살기 힘들다고 하네. 빽햄이고  브라질닭이고 소비자는 선택할 권리가 있으니 안먹음 그만인데 아무생각없이 물어 뜯는구나 진짜 최악이다.',
  '쿨한 두 스타❤',
  '전세사기는 영어로 뭐라고 하나요?',
  '요즘 PERSON_023 영상많은거 좋네 재밌다 ㅋㅋ',
  '개혁안하면 적자나서 못받는거였다 이건 잘된거다',
  '뭐 청년들 2030들 시민단체들어가든 시위를 하든 정치적 활동을 하는 것 자체를 부끄러워하는거같은데요\n그거 알고밀어붙였겠죠',
  '코스피농가 살릴려고 주식도 반값 세일했다는 소문듣고 왔어유 ~',
  '17:07 현진이 볼때마다 느끼는 건데 정면도 물론 잘생겼지만 측면이 ㄹㅇ 게임 캐릭터 같고 날티나게 남자답고 잘생겼음,,👍 두상도 동그랗고 이마~콧대 라인이 정말 아름다움',
  '아이언맨 곧인듯',
  '아니 무슨 보스몹 광역도발도 아니고 ㅋㅋㅋㅋㅋㅋ 야노시호누나 당장 비행기로 날라올꺼같은데요?ㅋㅋ',
  '근데형님들 이정도면 구냥 없애는게맞지않음??? 왜케유지하려고애씀?? 첫단추부터 잘못낀거같은데',
  'PERSON_023 먹으니까 보기 좋네 ㅋㅋ',
  '본인도 손해보고 소비자도 손해보면 햄을 왜파는건가요?',
  '얼마나 힘들었으면 그랬을까..ㅠㅠ \n그심정이해갑니다.. \n화이팅입니다!!',
  '요즘 댓글다는 애들 능지나 무차별 혐오하는 애들 많네 장사꾼이 자기 제품 최대한 가격내려서 판걸 사과하라 하고 물건 파는 사람이 돈벌려고 물건팔지 자원봉사하려고 물건파냐',
  '해외살이 10년넘었는데 이분은 좀 영어를 가르치는게 어디 강남 대치동 학원에서 알려주는 영어임...\n보니까 4개월;; 어학연수갔다온걸로 무슨 교포2세마냥 하는데..어우 쫌..스스로도 창피하지않나싶네요;;ㅎㅎ;;;;',
  '이미 사과문 올렸고 반성하고 있다고 하셨으니까 선 넘는 악플은 그만 답시다',
  '집에서 여유롭게 감상하려다 삭제된다는 말에 걸어가면서 보는중이에요~',
  'PERSON_002 데뷔 D-2!!! 데뷔곡 너무 기대된다💙🩷💛💚💜',
  '정말 암담하네요..',
  '농가를 지켜주시는 대표님을 어벤져스에 추천합니다',
  '이제는 그 누보다도 도파민과 함께 즐기고 계시는 아조씨',
  '사과하고 입장문 내줘서 고마워여!! 앞으로 한번더 성장하는 PERSON_016 되길 바래요!! PERSON_016 화이팅!!',
  'PERSON_074~ 빽햄 사태(라뇨?) 이후로 괴식만드는 컨셉으로 바꾸셨나요? 예전에는 그래도 사람 먹는 음식을 소개해줬는데 말이죠~~',
  '1:21 신길동 피솔킬왕',
  '100만원 스시 가자\n와사비도 비싼거 사서 직접 갈고\n우니+단새우+가리비 관자 감태에 만거 한번 먹으면 극락 맛보실듯',
  '100만원 분식 어떠신가요 ㅋㅋ\n떡볶이랑 어묵 김밥 튀김 요런거\n세트로하면 100만원 채우기 좀 수월할거같은데\n맛도 다양하게 보실수있구요 ㅋㅋ',
  'ㅠㅠㅠㅠㅠㅠ월요일의 단비 귀욤보아',
  '벤치왕님이 뭘 아시네요.... 요즘 어항이 아니더라도 옆판은 90% 이상이 다 강화유리 케이스인데 최소 중급기만 가도 감성을 충분히 살릴수 있는데... 고급형은 말할것도 없고요. 근데 그 다보이는 옆판에 떡하니 보급기가 들어가있다? 꼴뵈기 싫겠죠... \n그냥 이 감성이라는건 인테리어 비용이라 생각하면 똑같습니다. 인테리어 안해도 사람 살아가는데 아무 상관없어요. 근데 하면 깔끔해 보이고 좋잖아요...',
  '아니 PERSON_048 생각보다 잘하는데? 이정도면 성장가능성있어\n\n\n\n\n\n\n\n\n는 구라고 멸망전에서 차라리 정글 서폿으로 점수 하마할빠에 가성비 탑으로 출전해서 탱커만 하는게 더 빨리 우승할듯 ㅋ',
  'PERSON_003 OUT',
  '미국 4개월 있었다며ㅋㅋㅋㅋㅋㅋㅋ 존나얼탱이 개터지네',
  '앞으로 PERSON_048 정글 못한다고 욕하면 안되겠다. 탑은 ㄹㅇ 개족같네',
  'PERSON_061 힘내세요 그래도 해명할건해야된다고 봅니다 힘드시겠지만 추스리고 제대로된 해명문 기다릴게요',
  '처음 댓글 달아봅니다\n이 댓글을 씀으로써 배터리를  소비하여 스마트폰 농가와 배터리 농가를 살리고 배터리 충전을 위해 전기를 소비해 한전 농가도 살리고 있습니다 감사합니다.',
  '도파의 서폿론',
  'PERSON_039 유튜브계의 김혜윤이다...',
  '일부러 방송감있게 ㅈㄴ 던지는거죠? 말이 안되는데',
  '100만원짜리 피잔데 도구도 안갖춰져있고 ㅡㅡ아쉽네',
  '살이 다시찌내 ㅋㅋ',
  '탑 진짜 못한다',
  '국민들한테 동의도 안 구하고..\n그냥 욕밖에 안나온다',
  '얘 일부러 시청자 복창 터지는 컨텐츠 하나?',
  '13살 때 ID peace B로 맹랑하게 춤추고 노래하던 PERSON_016 봤던 게 엊그제 같은데 벌써 그로부터 26년이 지났네. 세월 참...',
  '4050 얘네들은 진짜 최악중 최악의 세대임 얘네는 스스로 지들이 산업의 역군이라 진지하게 생각 함 인생을 윗세대가 일궈놓은 업적으로 편하게 따뜻한 밥 먹고 편하게 자고 큰 주제에 젊은이한테 한다는 말이 따뜻한 밥먹고 뜨신 이불덮고 잤다\n니들은 안그랬어?',
  '우라라는 근본적으로 장유유서 문화/ 586어른대우 문화 자체가 하루 빨리 사라져야됨. 그래야  재들도 긴장하고 ㅈ되는데로 안하지. 에휴',
  '인기영상 가자',
  'PERSON_023 너무좋네',
  'PERSON_039 은근 케미여신인듯,, 배우계에 김혜윤이 잇다면. 유튜버엔 PERSON_043 잇다',
  '몇킬을 쳐먹었는데 케일한테 한틱으로 이기냐…. 진짜 레넥들고도 이길수있을듯 음음!!! PERSON_048 이글 보고 꼬우시면                  노틸러스 그랩#서폿차이 친추하고 1대1 뜹시다',
  '1:49 가만 보면 제작진이 진짜 제일 즐김ㅋㅋㅋㅋ',
  'ㅋㅋㅋㅋ PERSON_029 너무 조아 !!!!ㅋㅋㅋㅋㅋㅋ',
  '국민연금이 무슨 국민연금임?\n기업들 승계시켜주는 정경유착 비상금이지\n지들 맘대로 쌈짓돈처럼 뽑아먹는돈',
  '0:11 이렇게 아무리 사도 안되는 치킨값 올리기인데 이걸 해내는 우리나라 치킨 브랜드들 ㅋㅋ 진짜 역겹다',
  '몰라서 그러는데 잭스가 존야를 가나요…?',
  '스테이는 아닌데요, 현진님 용안이 원래도 잘생기신 거 알았는데 생얼도 잘생기시고, 연한 화장도 잘 어울리시고, 센 얼굴도 안 가리고 다 잘 어울리셔서 눈 호강 제대로네요',
  '실버에서 겜하면서 킬따면 크랙이러고 재능있는거같다고하네 ㅋㅋㅋ 실버가맞아 상호형은',
  '근데 어도어 계약이 유효하다는\n판결되면 그래도 나가겠다 하지 않는\n이상 6000억 낼 일은 없는데\n6000억 내는 걸 왜 확정처럼 다들 말하는거임? 설마 그렇게 돼도 나간다고 할리는 없겠지',
  '7:41 이거늨ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  'ㅁㅣ친거 아냐 ㅋㅋㅋ ㅋ 이 ㅇㅏ조씨 ㅋㅋㄱㅋㅋㅋㅋ',
  'PERSON_061 힘내라\n악플다는인간들도 같은 상황이라면 똑같이했을거면서 이중잣대 대는거 역겹다 정말\n\n내돈앞에선 이기적일 수 밖에 없지;;;',
  '오버클럭이머에여?',
  '39:10 하 개귀엽네 돌았나... ㅁㅊ겠다',
  '이럴 거면 차라리 없애는 편이 나을 듯 싶네요. 젊은이들만 또 고생하며 불만이 제기되는 상황이니까요. 말도 많고 탈이 많은 국민연금 문제에요!',
  '나 피시방 알바하는데 가끔 오시는 손님 중에 틱 있는 분이 계신데 그분도 플레더라... 그냥 그렇다고..',
  '8:55 용의 지휘',
  '직업  : 파이터 \n특기 : 야노시호 화나게해서 스파링',
  '왜 판타지 물 에서 영웅이 추앙받는지 알겠음 정치인들 그냥 악마 그 자체임',
  '100만원짜리 비빔밥 궁금하긴하다',
  '인직이형 나 도덕에서 선풀달기 하고있어 중학교 2학년이야 형 피온에서 처음봐서 윳겨서 구독 했는데 먹방이랑 중고 등등 컨텐츠 해줘서 재미있게 보고있어형 영상 꾸준히 보고있고 형보면서 많이 웃었어 형 ㅃ',
  '6:48 우왕 감동이다,, 그때 콘서트 왔을때가 딱 PERSON_011 데뷔 16주년이녔는데 센스있게 2008년산 와인에 문구도 자세히보면 16주년 축하하고 공연잘보고갈게요 이런거 써있음!!',
  '스테이는 아닌데 현진님 너무 귀여우시다 ㅠㅠ',
  '권지용 컴백 후로 왜케 귀여운 느낌이 됐지?? ㅋㅋㅋㅋ',
  '형 이렐판은 도저히 역겨워서 넘겼어 미안해...',
  '40:16 40:19\n머리색 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아 바뀌었잖아',
  '진정한 시과영상 올리고 pb제품 그만 만들고 프차관리에 전념하겠다는 말만 했어도 이정도 까진 아니였어요..........',
  '피자에 소주는 거하게 취했을 때 맛있습니다',
  '야 뭐 됨?',
  '너무 귀여워요 언니 ㅋㅋㅋㅋㅋ이제 진행 넘 잘한다~~~!!!!!',
  '청년빈곤율은 어쩌고',
  '100만원 마라탕 각이다!!',
  '블라인드테스트해주세요~ 7090xt 5070ti 5090\n상급기분도 테스트꼭참여해주세요',
  '씹\n팔\n육\nㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '탁핵보다 빠름 ㅋㅋ',
  '우리나라 인간들 냄비 근성은 알아 줘야 함. 좀 기다려 봐라 수습 한다 잖아.',
  '민지가 좋아하는 랜덤 게임 \n랜덤게임 \n게임스타트\n칼국수 칼국수 칼국수 칼국수 칼국수 칼국수 \nUh uh-huh uh-huh\n칼국수 칼국수 칼국수 칼국수 칼국수 칼국수 \nUh uh-huh uh-huh',
  '11:12 종교 어필하고 뿌듯한 표정하는게 왤케 웃긴건지 ㅠㅋㅋㅋㅌㅋㅋㅋ',
  '다본후기 : 존나달다...  너무 설레서 숨이 안쉬어짐....  업로드 2시간만에 좋아요 3천 ....? 이정도 화력이면 월간데이트  넷플이랑 계약하자',
  'PERSON_023 월급 더줘라',
  '아 ㅋㅋㅋ 로마의 전통 놀이 마렵네',
  'PERSON_056 이렐궁날리는거 4대기 마려우면 개추 ㅋㅋ',
  '기존 안냇던사람에게 소급 청구해야지 지들안내고 미래세대에 부과하니 진짜 뻔뻔하다',
  '이럴거면 윗세대랑 아랫세대랑 영혼의 막고라 어떰?\n역사적으로도 대가리 걸고 데스매치하는게 최고의 해결책인데.\n애초에 문제의 원흉을 없애버리는게 k해법 아니었음?\n구세대든 신세대든 하나 없어지면 해결되는 문제니 막고라나 뜨자고 ㅋㅋㅋ',
  '계속 100만원 컨텐츠 하려면 결국 요리결과물의 크기도 커져야 될듯 재료를 어느정도 떄려넣을 수 있어야 단가가 맞을듯',
  '1등',
  '요약 : "못돼처먹은 어른과 노인들의 아이들과 2030 미래 팔아먹기 작전 대성공"',
  '안녕하세요 감식반입니다\n현장감식 하겠습니다 아직 따뜻하네요',
  '에휴 ㅅㅂ 내 18분 날렸네',
  '실버 가니깐 수준 맞네',
  '엿같은거 아직도 115만이네',
  '100만원짜리 PERSON_023 볶음밥 가자',
  '야 너 최악의 재능러라니깐',
  '23:26 치원님 진짜 초면에 죄송한데요 진짜 미치신거 같아요.... 진짜 너무하세요... 어떻게 그렇게 솔로의 마음을 뒤적이다 못해 엎어치기를 하실 수가 있어요.... 사귀어줄 거 아니면 그러지마요.... 아 내가 다 설레... 아 오늘 밤 잠 다 잤다.....',
  '나중에 586들 은퇴후에 다시 고쳐놓는 법안 통과됐음 좋겠다..',
  '2025년은 1960년대생이 65세가 되는 해입니다^오^',
  '32:00 노래 안 부른 거까지 완벽해서 죽었음',
  '내 기준에서 PC영화의 마지노선은 킬빌임.\n여자도 수련 뒤지게해서 쎄진거고, 복수를 위한거여도 서사가 있으니까',
  '10:56 아 미친ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  'ㅋㅋㄱ4개월다녀온게 유학생활이라고 하고 다녔어....?',
  '스키즈 매니져들이 뽑은 이 멤버로 살아보고싶다 1위 현진👏 거울 보면 기분이 좋아질듯, 얼굴피지컬 쏘굿, 반삭도 잘어울려서 등 이유 납득',
  '요즘 나락을 참 잘 가네',
  '대한민국 역사상 가장 부유한 세대가 가장 가난한 세대한테 등골 빼먹는 시대 ㅋㅋ 취업문은 가장 낮고 적금만 넣어도 너도나도 집한채는 거뜬히 살수있었던 세대가 이제 은퇴할때 되니 구인배수 0.28인 청년들한테 마지막 등골까지 다 빼먹고 놀아보겠다고 선언 국회의원들 평균 나이만 봐도 그냥 답이없는 미래를 가진 나라임 악착같이 영어공부해서 이민이 답이다 이제 이 침몰하는 배에서 누가먼저 탈출하냐 싸움이다',
  '다음엔 자장면해주세요 형',
  '오늘도 인직님의 잘 먹는 모습을 보니 좋네요.좋은영상 감사합니다',
  '인간들이 이렇게 악합니다. 악해요... PERSON_006 선생님 힘내세요. 제 작은 댓글이 이 거대 악을 이길 수 없을 걸 압니다. 그래서 더 슬프지만.. 정말 무섭네요.\n골목식당도 출연료도 안받고 전국민이 재밌게 보고, 막상 지역농민들은 감사하게 생각하는데 이제와서 미디어를 타서 손가락질하는 대중들.. 이들의 삶 속을 들여다보면 불법/위법 투성이입니다.\n스마트폰 하나들고서 쓰레기 아무데나 버리고, 과태료 안물고. 불법동영상보고 안걸리고, 연예인들 잘못하는거 남인생 지적은 자연스럽게하고, 막상 자기들 친척네가서 한마디들으면 발작을 일으키면서.. 자기네들 친구들 술먹고 실수하면 괜찮다하면서 미디어에서 누가 실수하면 그 사람이 죽을때까지 욕하고. 많이 잘못된사회입니다. 그런 사회에서 고군분투하는 PERSON_074..\n정말 힘드시겠습니다.',
  '근데 진짜 궁굼해서 그런데 이사람 논란 터진것좀 알려주면 안됨? 지금까지 봐온걸론 걍 본인 상품 가격 측정이랑 닭 원산지 브라질산 썼다고 논란인것 같은데 진짜 뭐가 문젠지 모르겠어서 그럼... 혹시 내가 모르는 뭐 다른 문제가 있어서 이렇게 까이는건가..',
  '여기는 PERSON_029 제작진분들이 만난게 완전 천생연분... 제작진분들 다 넘 잘하심',
  '머리뭐임',
  '깔깔깔 웃는 스텝 너무 좋아요. :))😊😊너무 유쾌해요 ㅋㅋㅋ ㅋㅋㅋ',
  '그냥 따로 따로 하자니깐요? 공평한거 좋아하시잖아요\n가장 공평한 너희건 너희가 우리건 우리가\n\n개혁이 아닌 개악!',
  '팔레트를 들으면서 같이 25살로 돌아간느낌이었어요  아련한 향수같았습니다',
  '4:16 첫만남부터 꽃으로 혼란을 주는 FOX\r\n5:06 편지 선물? 결혼 안 하면 사형\r\n5:19 멘트 뭔데 미친 인프피한테서 상상할 수 없는 멘트\r\n6:06 PERSON_039 그림 그렸다고 준비할 때부터 PERSON_039 생각했다는 어필? 사형\r\n6:17 그러면서 편지에 고백은 안 한 부끄러움 모먼트? 귀여워.\r\n7:11 예쁘다? 그 말하는 본인 눈도 초롱초롱해짐\r\n7:20 찰스님의 솔직함에 경계심 풀어지고 웃는 인프피? 귀여워.\r\n8:20 서로 원했나봐요??? 멘트 장난함? 얼굴 무덤덤하게 하는거 개치임\r\n10:03 옵빠? 근데 그냥 오빠가 아니라 "옵... 옵빠?" 말 더듬으면서 했으니까 합격\r\n10:26 밥 사주는 사람 좋은 사람\r\n10:55 나이 안 본다고 여지 주는 남자.\r\n11:08 기독교 집안이라고 계속 어필 노력하는 인프피... 귀하다\n\n영상 40분짜리라 적다가 포기함 나 그냥 즐길래 이 두 사람.',
  'ㅈ됐다!!!!!',
  '이 유튜브에서 계속 파묘당하고 있는데 안닫는것도 대단하네',
  '댓글 진짜 잘 안다는데 진심 짜증난다 ㅋㅋ',
  '전 대표와의 의리는 이미 충분히 보여줬다 이제 돌아와야한다. Kpop역사상 최악의 병크 사례로 남기 싫다면 그리고 팬과 kpop의 모든 종사자들에 대한 존중이 남아 있다면.',
  '2030 뜯어 먹는 정의로운 똥86을.',
  '100만원치 돼지 한마리로 요리 ?',
  'GD는 이제 그만 나오자. 전원일기 생각난다 이제.',
  '? 타팬인데 까까머리여도 왜리렇게 잘생기셨죠 너무 멋있으심 골드키위…?',
  '그냥 똑같은 행동 반복만 하면 만판을 해도 똑같은 실력일텐데...\n하도 욕 먹고 시비 걸리니 싫은소리는 다 억까라고 하네\n세상이 만든 괴물이다.',
  '약속의 6개월 다가왔네.\n슬슬 복귀각 나오겠다. 수익창출 끊기는게 6개월 이니까.',
  '고작 4개월이면 그냥 캠프수준아님? ㅋㅋㅋㅋㅋㅋㅋ 난 중고등학생때부터 미국에서 살았는줄 알았네',
  '형님 어쩌다 이렇게 되신겁니까…?😢',
  '19:52 밥 먹는거 보는거 개설렘 ;;',
  '관상은 과학입니다.',
  '아조씨 요즘 집 들어 가기 싫쵸?! ㅋㅋㅋ못들어가겠는데',
  'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 목숨 두개세요?',
  '더본 뉴스 언제 함? 얘기 할꺼 정말 많지 않아유?',
  '뭐야이거? 미치겟네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '와 진짜 귀엽다 People my favorite songs still!!💕🙌🏻',
  '중국산 메주 쓰신다는거 사실인가요??',
  '에휴',
  '14:26 뭘로 입을 닦으시는거야ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ앞치마 아닌가?ㅋㅎ',
  '100만원 텐동 어때요?',
  'PERSON_049\n가렌\n말파이트\n뽀삐\n레넥톤\n\n외워 그냥 딴거 하지마 제발',
  'PERSON_011 지드래곤 듀엣의 butterfly를 듣고 싶습니다!!!!!!!',
  '듀엣구간이래 우와 진짜 웃겨요❤❤❤❤',
  '너무 좋아서 내 뺨을 때리고 있어요',
  '미친거야..정말 미쳐버린거야….❤\n27:21 듀엣은요….?',
  '오우 벌써 맛있어 보여 버리고',
  '최고다👍👍제니와 지니의 만남ㅂ❤️❤️❤️❤️❤️❤️❤️❤️❤️\n파리에 꼭 가시길💪🏻💕\n보는내내 행복했어요🙏',
  '100만원짜리 볶음밥 해줘 형',
  '이거 정규시리즈로 해줘라 ㅈㅂ',
  '나는 내기 싫은데',
  '남자는 뇌가 중3에서 멈춘다더니 ... 진짜네 😂😂😂',
  '항상 고맙습니다 ❤️ 😊',
  '간만에 박상민 노래 부르는줄',
  '아조씨 다시는 상처받지 마세요. 세상은 원래 그러니까 그냥 살어야되요\n아조씨 가족은 위선이 없어서 좋아요\n위선에 쩔어 망해가는 우리나라에 요즘 희망이 보여요\n한가인 욕 많이 먹던데 한가인이 착한척 말잔치 할줄몰라서 그렇다는거 사람들은 모르나봐요\n우리나라는 착한척 말잔치에 너무 잘 속아요\nPERSON_029 한가인 상처 받지 말고 있는그대로 쭈욱~ 화이팅',
  '와 진짜 수퍼모델은 다르다... 웃길라고 입은거일텐데 진짜 개멋있음 ㅠㅠㅠㅠㅠ',
  '야야,,, 벌써 2시가...?. 잠은 다잤다 ,,,,',
  '안타까워   참 너희들 너무 하다고 생각 안하냐 상장 한게 죄냐...더럽다 국민들',
  '형 100만원 비빔밥 어때??',
  '국가에서 운영하는 다단계 사기인거져',
  '이제 탑으로 멸망전나가고 다음은 미드인가요?',
  '늙으면 추하고 추악해지지 짐승들 처럼 국회가 딱 그렇다',
  '제니 진짜 걈다살인듯 요정재형도 찐천재도 진짜 출연잘한듯 ㅋㅋㅋㅋ 찐천재는 제니 출연한거중에 젤 웃김 ㅋㅋㅋㅋㅋ',
  '나중에 우리가 나이먹어서 정치권 장악하면 그때 7080 세대 국민연금 줄이면 됨.',
  '아니얼굴이 대단하노',
  '최악의 세대 70년대생',
  '좋은거 잘 배워갑니다 30년 뒤에 두고보세요',
  '더 내고 더 받기로 결정난 건 일단 ok\n\n근데 그러면 지금까지 덜 냈던 윗세대가 지금 ‘당장’ 더내기+많이 덜 받기, 우리는 앞으로 ‘점차’ 더 내고 덜 받아야 되는거 아님?ㅋㅋ',
  '브라질 농가살리는 PERSON_006 브라질 경제대통령으로',
  '홍탁집 사장 : PERSON_072 저한테 솔루션 좀 받으실래요. 제가 초심 하나는 누구보다 자신 있거든요.',
  '영감님 살아계시다면 당근 흔들어주세요.',
  '8:36 PERSON_028 PERSON_023 서로 백태 자랑하기ㅋㅋㅋ',
  '형 주식 날렸어요?',
  '미필이 많아서 그런가 군혜택을 축소해버리네ㅋㅋㅋ\n산유국 되지 않는 이상 답없네',
  '정글은 이경민밸 탑은 킴성태밸',
  '2:04 개귀여움 ㄹㅇ',
  '여러분 ph-1 노래중에 365&7 이게 진짜 찐설렘노래입니다… 내가 유일하게 아는 피에이치원 노래이자 봄만되면 플리에 넣는 노래… 나한텐 벚꽃엔딩보다 365&7임… 개애애애애애설렘 이거보고 들으니까 벌써 벚꽃핌 ㅠ',
  'PERSON_001 많이 사랑해 PERSON_002🩵 언제나 행복만 해줘',
  '하 진짜 두번다시 피오라 이렐 하지마쇼..',
  '35:00 개웃기다...............인프피남성의 투명한 질투................ 개웃기다고 나이제안들어ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '박치기공룡도아니고 좀 공부하고 하면안되냐',
  'INFP가 질투한다 = 생을 마감할 때까지 함께 하자는 뜻',
  'PERSON_049 그화법쓸때마다 뺨마렵다 하 드럽게못하면서 목청만뒤지게크고 진짜 지가 못한걸 남한테 떠넘기는 습관은언제쯤 고칠까ㅋㅋ',
  '100만원 햄버거 드가자',
  '이 영상 이후로 월간데이트 안 올라와도 그냥 눈감고 넘어가드릴게요…',
  '아아아아 보보싶이었는데💛💛💛💛💛💛💛💛💛💛💛',
  '그냥 추후에 80년 90년대생들이 국회의원 될 때 우리도 우리마음대로 법안 만들어서 586세대 돈 그냥 뺏으면 안돼나 ㅋㅋㅋ',
  '여기 조롱댓글 작성자들의 공통점은\n\n누군가 잘되면 배가 아프고 누군가를 짓밟았을 때 행복감을 느끼고, 현실세계에선 누구보다 쿨한척하지만 속으로는 주위사함들에게 열등감과 피해의식에 그걸 자기자신이 아닌 사회탓으로 착각하면서 오늘도 온라인에서 누군가를 조롱하고 거기에서 성취감을 느끼는 부류들.\n\n이걸 보고 지랄하네라고 생각하겠지만 자신의 인생을 돌아보고 변화하시길 바랍니다. 부디 부정적인 방식이 아닌 긍정적인 방식으로 인생을 행복하게 만들어나가시길 진심으로 응원합니다.',
  '소시오패스 특징에 완전히 부합됨 ㄷㄷㄷ무섭다',
  '형 이 영상 내용은 동의하기 힘든데? 평소랑 다르네',
  '댓글농가는 제대로 살리셧네유',
  '형 다음은 100만원 비빔밥 가자',
  '15시간째 상주 중',
  '네이마르 입니다.\n우리나라 농가 살려주셔서 감사',
  'ph-1이 부럽다가 PERSON_039 부럽다가.. PERSON_039 저랑도 데이트해요 여자긴 한데… 아니 고딩때 ph-1 덕질하고 앨범 맨날 스밍했는데 여기 나오셔서 눈 튀어나왔잖아요.. 역시 내가 보는 눈이 있어 The Island Kid 앨범 명반인거 다들 알아주라..',
  '정치판 아무리 누가누가 덜 병신이냐라지만 진심 미래없는 땅놀이 넘어서\n하다하다 애들 코 묻은 돈 뺏어먹겠다는게 보여서 치사빤스 똥빤스가 따로없음\n개 역겹다..',
  '근데 PERSON_006 왜 까이는거임? \n당연히 음식장사하는 사람이 음식 광고하는게 맞는거 아님?',
  '100만원짜리 화채 해줘',
  '고려장이 옳았다',
  '이것만 기다린 사람은 개추',
  '기분좋게 치킨먹으면서보는데 도저히 못보겠어서 11분 보고 딴스트리머꺼 보러갑니다',
  '9:01 스킬 다 썼는데 챔피언한테 맞춘 스킬 Q 1번이 끝인 게 개쳐웃기넼ㅋㅋㅋㅋㅋㅋㅋㅋ 방송신이다 이정도면ㅋㅋㅋㅋㅋ',
  '와 장발아이콘 삭발유행 하는 메이컵마다  잘받기로 유명한 현진 드디어 나오네요 !! 얼굴천재에 분위기천재라 뭐든 넘좋다 ㄷㄷ',
  '뜻끔 없지만 정말 순수하게 궁금해서 질문드립니다! 혹시 영상에 미국 대학교도 나오고  연세대도 나오는 같은데 달씨님은 어디 대학교를 다니기는지 아님 두개를 다 다니시는 건지 궁금합니다! 여쨋근 오늘도 영상 잘봣습니다!!❤',
  'PERSON_048 진짜 제발 탑 그만해줘 영상을 안볼 순 없는데 나 너무 힘들어',
  '아니 진짜 PERSON_039 선업튀의 혜윤님 같음\n준빵조교님에 이어 Ph-1님 입덕함ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ너무 매력있으시네….근데 PERSON_039 왜 점점 더 예뻐져? 진짜요..',
  '탈조선이 미래다',
  '한국인이니 100만원 비빔밥 해보죠 ㅋㅋ',
  'PERSON_048 바르셀로나 팬 할래?',
  '형님 차도 없으신데 넷또카훼서 주무시려고 그러시나요',
  '지디는 주변에 좋은 사람이 많은 이유가 지디도 좋은 사람이여서 그런 것 같다 ㅠㅠ',
  'PERSON_047 재미있어!',
  '인동 1위!! ㅊㅋㅊㅋ🎉 지디님 최고😊',
  '와 보면서 진짜 감탄하면서 봄 ….. 사람얼굴이 어떻게 저렇게 생길수있냐 개잘생겻네',
  '멋지다 두분!!!! ❤',
  '약속의 10월 기대해볼게요!!! 진짜 재밌을것같아요',
  '피자 먹을 때 눈 초롱초롱한 초롱직 기여워',
  '히샬리송입니다. 우리농가살려주셔서 따봉',
  '황유 기다리는 1인',
  '난 봄',
  '좋아하는 투 샷 .. 소중해.. 💗',
  '전세사기 떠넘기기 썰을 영상으로 올린게 신기하네',
  '와 비쥬얼 쥑인다~',
  '여자최애와 남자최애의 조합 미쳤더...@!',
  '매력덩어리 햄, 쌈바 치킨, 이번엔 감귤 ㅋㅋㅋㅋㅋ',
  'PERSON_025 방지턱 조심해',
  '17:06 \n극락 좌표 공유합니다... \n얼굴로 스테이 기 살려주는 현진이 최고',
  '근데 PERSON_039 편집을 너무 잘하시는거같아요.... 러닝타임 긴데 하나도 지루하지않고 자막도 센스범벅+왕웃김.. 꽤 긴시간 통으로 촬영하다보면 편집하기 힘드실거같은데 노력과 정성이 너무 느껴져요..🥹 너무 무리하지말고 오래봐요 우리~🤍',
  '와근데 새삼 진짜 잘생겼다',
  '어느새부터 연금이 세대 간 폭탄 돌리기가 된 것 같아 슬프네요',
  '타팬인데 아니 빡빡머리 저렇게 잘 어울리는 사람 처음 봄 우와 개인적으로는 독없뱀 메이크업이 더 좋은데 독있뱀은 자꾸 들여다보게 되는 느낌이라 시선을 사로잡아버림 걍 뭔들이다 뭔들이야',
  '미쳤다 한번도 덕질 해본 적 없는데 아이돌 영상 보면서 웃어본게 처음임 입덕을 내가..????',
  '한국은 PERSON_002 감사해야 하는데 차별하고 자유를 빼앗는 폭거는 멈추고 해방하고 사과해 주세요.한국인들에게 도덕을 가르쳐 혁명을 일으킬 수 있는 것은 PERSON_002 밖에 없습니다.언제까지나 시대 늦은 생각으로 한국사회는 한심하다.',
  '비싼값의 햄을 강매 한것도 아니고 싫고 비싸면 안먹으면 되는거지 그리고 아무리 안팔리는 부위라도 한돈이랑 수입산은 가격이 다를거고 여기 악플다는 애들은 정신이상자 인가? 아니면 경쟁사거나 경쟁사면 인정',
  '저도 주머니 돈이말라 힘듭니다 제주머니 농가도좀 부탁드립니다',
  '오호~ 무대응 정면돌파로 정했네유~ 그냥 죄송합니다 생각이 짧았습니다. 가격책정 다시하고 새로운모습으로 다시 빽햄 출시하겠습니다.  하면 여론도 다시 넘어올텐데 3주 생각한거치곤 영,,',
  '실버호한테 개처맞는상호리',
  '피지컬은 모르겠고 뮤지컬은 잘 봤습니다.',
  '흠....',
  '그냥 ph-1이랑 12월간데이트해주세요ㅋㅋㅋㅋㅋㅋ',
  '형 너튜브에 하나밖에 없는 목숨 걸었어? 형수한테 어떻게 살아 남을려고! 형은 형수보다 총알도 부족하잖아~~ 아! 든든한 100만 구독자가 있네! 그래서 형은 살아 있는것! 구독자 떨어지면?\n 형은 아조씨의 롤모델이야!😅',
  '곧 브론즈에서 만나겟네 두근두근',
  '세상 어디에 이렇게 귀여운 39살이 있음? 우리 PERSON_016 낼모레 마흔인데도 아직도 예전 데뷔때만큼 파릇파릇함 ㅎㅎㅎ id peace B 시절 그립다아~',
  '100만원 치킨 하나 이제?',
  '이 얼굴을 보고 어떻게 평온하게 메이크업을 완성하시지.. PERSON_060 전문성 미쳤다(positive)',
  '크르릉 거릴때 깨물고 싶어서 어떻게 참으신거에요 와 현진이 미모 미쳤다...........',
  '와 탑은 진짜 토 나온다 형 ..',
  '이번거 침묵하면 다음 세대 태어날 아이들이 힘들어 진다 2030에서 끊어내야 합니다.',
  '너무 좋아여 이런거 ㅎ',
  '영상 보니까 4개월 동안 쳐먹고 놀러다닌게 끝인데 유학맞는지?\n관광만 오지게 한 거 같은데 ㅋㅋㅋㅋ\nPERSON_061 궁금한게 있는데 미쿡에선 사기피해자가 또 다른 피해자한테 사기 쳐도 무죄임? 사회적으로 문제 없음?',
  '막말로 재해라도 일어나 입 줄어드는게 희망이라 개판임',
  '이걸 빨아주는 놈들이있네 ㄷ 대단하누',
  '너무 작은 것 같은데?',
  '피자든 치킨이든 트러플에 캐비아 올리면 100만원 쑥딱임',
  'PERSON_072 믿고 지지합니다 시민들에겐 한없이 실보다 득이 많은 기업인데 사람들 참 너무하네요;',
  '불안해서 죽것네... \n\n대낮에.... 저 큰 마이크 뭐냐구!!!!!!',
  '18:02\n썸네일 보고 너무 새로운 조합이라 그냥 그것만으로 재밌겠다 했는데 생각보다 너무 설레서 당황 (positive',
  '내야 했을 사람들이 안냄\n지금의 청년,중년 세대 내야함\n후에 이번과 같은 일이 반복됨.... \n결론 지금 태어나는 아가들아 미안',
  '왜케 귀엽고 이쁘게 생김??',
  '진짜 창의적으로 못한다',
  '돈 막갈기네',
  '전세사기 꿀팁 공유 감사합니다',
  'ㅁㅊㅁㅊㅁㅊ 제니야 ㅜㅜ 김제니!!!!!! 너왜여기서나와ㅜㅜ 진경이모 너무..너무..ㄴ고마워요ㅜㅜㅜㅜㅜ 아ㅜㅜㅜ\n)))) ㅁㅊㅁㅊㅁㅊㅁㅊ 죽자죽어 10월에..? ㅜㅜ 좋아요 너무ㅗㅈ좋아요ㅜㅜ 내가 너무 기뻐ㅜㅜ ....\n후우ㅜㅜㅜ~~~~ 워너 롹윗 제니~ 킵유얼헤어던네일던라잌제니..🥺',
  '왜 내돈을 니들이 합의하고 자시고 하는건데?',
  '형님 100만원짜리 샤브샤브를 보고 싶습니다',
  '나라는 20~40은 중심이 되어야지 왜 5060 위주로감?',
  '솔직히 재료들 너무 뻔하다 PERSON_028 좀 신박한 거 들고와라',
  '100만원 마라탕, 100만원 파스타',
  '솔직히 롤에 재능이 딱 10년전 정도인게 아닐까\n버스나 듀오 없었으면….',
  '칼에 뭍은 것 만 먹어도 만원은 나오겠다. 졸라 맛있겠다😢',
  '김동현 말이 생각나네\n일방적으로 혼나는데\n싸웠다고 한다고 ㅋㅋㅋ',
  '비빔수제비는 원가가 어떻게 되나요?\n빽수제비인가요?\n빽햄넣어도 맛있나요? 굽는거보다?\n수제비농가에 도움주나요?\n근데 텐션이 왜그래요? 빽햄많이 못팔았나요?',
  'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 조만간 삭제 예정이네',
  '아틀란티스소녀 ...every heart ...  everlasting... song with no name  이 노래들을.. 들으면 그시절...PERSON_016 그시절 내가 떠올라 가슴이 먹먹해집니다... 혹시라도 힘드신 일이 생기신다면 매일같이 PERSON_016 노래를 들으며 출근을 하고 자면서도 PERSON_016 노래를 들으며 힐링을 하는 팬들을 생각해 주세요 사랑합니다. 누나 응원하겠습니다.!',
  '내가 낸돈 맘대로 쓰고 부족하면 인상 ㅋㅋ 엉뚱한데 투자해서 말아먹고 환율방어한다고 다 써버리고',
  '아 이분이 그분이구나 ㅋㅋ',
  '감성 나온순간 이미 진거 할말이 그거뿐인거라 거름',
  '미쳤어ㅋㅋㅋㅋㅋㅋ뒷감당어찌하려고 그러냐구욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ  0점 우와또혼날것같애요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아니진짜신박하네',
  '586멸종 기원합니다',
  '100만원짜리 마라탕 안되나 재료좀 다양하게 😂',
  '와 이분뭐죠 귀엽다… 잘생깄누',
  '영어쓰고 유학다녀오면서 지식인인척 그냥 사기꾼 검은머리 외국인아님? ㅋㅋㅋ',
  '난 4년동안 스위스에서 살고있고 집도 내 소유로 있지만, 단 한번도 스위스에서 온이라고 안하는데 ㅋㅋㅋ 얼마나 교포 흉내가 내고싶었으면.. 진짜 구질구질하다',
  '다음엔 100만원 떡볶이 해주세요❤',
  '국개들아 곧 아래 세대들의 대규모 폭력사태가 일어날거다',
  '19:14 “기다릴게요”',
  '말도 안되는 대한민국의 정치판.\n자식들 잡아먹는 대한민국',
  '이거 근데 못한판만 모아서 올리는거 맞죠?',
  '진짜 지들이 세대갈등 만드는 스욋 5060',
  '사개월있고 미국대화법전수하는거 실화냐',
  '아  힐링 됬어여!!!!!!!!!!!!',
  '0:35 다음곡 아조씨 생일이네',
  '먹방 더올라오면 조켓다',
  '선생님.. 영상이 안 끝나요..ㅠㅠ 현생을 살아갈수가 업써요',
  '아 진짜 상장한지 얼마됐다고 온갖 잘못은 다 터지고 있네 주식 산 사람은 뭐가 되겠냐 ㅋㅋ',
  '연대 다닐만큼 똑똑하고 해외도 많이 다녀서 인맥도 경험도 풍부하고 협찬에 광고에 많이도 찍으면서 사회경험도 충분한 사람이 아무것도 모르는 사람한테 전세사기 떠넘기는게 잘못된건줄 몰랐다?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
  '형.. 엄마가 될거라는 가정을 버려.. 지금 결혼율도 박살났어 ㅋㅋㅋ 갈라치기 직접적인 타격을 받은 저주받은 90년대생들이 온다',
  '최악의 적폐세력 4050',
  '우리나라 청년들 정말 착해..',
  '야노시호 출연은 곧죽어도 싫은데ㅜ 타이틀은 알차게 써먹는 아저씨 ㅋㅎㅋㅋㅋㅋㅋ',
  '제니는 정말 오래오래 활동했으면 좋겠다..! 증말 독보적!',
  '제스쳐가 꼭 기안84가 떠올라용😂',
  '추잡한 노욕으로 가득찬 노인강아지들',
  '실망이에요',
  '망할건데\n뭔 걱정이고 ㅋㅋㅋ\n죽으면 사후세계 없다고 믿고 힘없는 새싹들 녹즙 쭉쭉 빨다 가라\n갓팔육',
  '욕하는사람들 이해가 안간다\n그냥 싫으면 안보면될껄 ㅋㅋ\n진짜 냄비근성알아줘야혀',
  '진짜 PERSON_023 개사기캐임 \n나오는 영상마다 존나 재밌음 ㅋㅋㅋ',
  '대리만족이긴한데 그돈으로 선한 영향력도 좋을것같다 ~',
  '100만원 파스타..?',
  '그리고 노인네들이 단단히 착각하고 있는게 선진국서도 조금 나이 있는 사람들이 하는거보고 지네도 괜찮다 생각하는데 그들은 개인주의 철학이 기반이 되어 벌써 오랜시간 비슷한 철학을 갈고 닦은 형태고 우리는 그냥 아예 다른세상 사람이 공존해서 사는거야 하..',
  'ㅈㄴ재밌네 ㅋㅋ 요즘 100만원 컨텐츠 보는게 낙임 많이해주세요~',
  '만두 1000개는 할수 있죠?',
  '인자기 살찌우는중',
  '저기요 아줌마 제정신이면 유튜브 접으세요',
  "20:28 지디 콘서트에서 빨간옷입고 '히사시부리' 그 톤이라 완존비슷❤ 스위치up ! 좋아하는목소리ㅜㅜ뭔가 고죠+루피같음",
  '억까 거르고 진짜 실버 골드 수준임',
  '이정도면 빽햄 마케팅 전략 아님??ㅋㅋㅋㅋㅋㅋ',
  '최초 계약 내용과 달라지는데 기존 계약자들은 계약해지를 못 함.\n\n반면 받고있는 노령층은 기본대로 계속 받음.\n\n왜 내 돈으로 남들을 먹야함.',
  '전세사기보고 찾아왔습니다. 소시오패스의 정석이신듯하네요. 남한테 피해끼치고 살지마세요.',
  '컴퓨터에 감성이 왜필요하죠?? ㅋㅋㅋㅋ',
  '와.. 그래도 좋은 일도 엄청 많이하셨는데.. 사람들이 그런건 다 잊어버리네\n대중들 진짜 너무하다..ㅋㅋ;;',
  '남편들은 마누라놀리는 재미로 사나봐 ㅋㅋㅋㅋ',
  '개설렌다ㅋㅋㄱㅋㅋㅋㅋㅋph1 급 호감',
  'PERSON_016 술 좀 줄이자............',
  '머야머야.. 둘 다 부럽습니다. PERSON_012 노래에.. 지디. 랩.. 정말.. 그냥 배가 부름..',
  '일단 나는 떠난다 화이팅!',
  '폭탄돌리기 성공해서 기분좋으시겠네 ㅎㅎㅎㅎ 아유 고마워라',
  '나 음주롤 할때랑 똑같네',
  '뭐랄까 준빵씨와 설렘의 급이 다르다..',
  '넘 이뿌❤',
  '고급재료를 추가해주세요 캐비어나 트러플 이런거..',
  '집에서 영상보고 뭐라하실까ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ너무 웃겨요ㅜㅜㅋㅋㅋㅋㅋㅋㅋㅋ',
  '국민연금 낸만큼 사람들 돈이 줄어서 경기 침체가 오겠지.',
  '오 두번째 100만먹방 !!!! 재밋겟다',
  '중학교 다닐때 PERSON_016 티비로 아틀란티스인가 넘버원인가 활동 할때 저 친구는 몇살일까 햇는데 나랑 동갑이였어...20살때는 mp3로 걸스온탑 모토 한창 듣고 머리는 PERSON_016 따라서 울프컷 따라 하고 다녔고 세월 참 야속하다 벌써 40ㅠ',
  '진짜 레전드 세대 ㅋㅋ 역대급 꿀빨다가 끝까지 이기적으로 2030 빨아먹겠다는 마인드 누구보다도 갈라치기를 조장하면서 경제랑 출산율 개박살내놨으면서 항상 결론은 2030탓 ㅋㅋ',
  '방송의 신이 맞긴하다 와근데 팀은 고트긴하다 어케이기지 ㄷㄷ',
  '다음 요리는 브라질 닭요리 소개해주세요 ㅎㅎㅎㅎ',
  '독도새우 한마리 35,000원 이라고????????',
  '홍지니님 Elsa한테 옷 빌려 오신거져? 그치만 또 200%소화해 내는 홍지니는 내맘속 최고  모델계의 Jennie임!!',
  '지금이라도 늦지 않았으니까\n잘못했다고 하고 들어갔음 좋겠다\n제2의 피프티 사태 또 보고 싶지않은데\n정말로',

In [ ]:
# 다른 형식을 Dataset
from datasets import Dataset
d = Dataset.from_pandas(df_train.head(100))
d

Dataset({
    features: ['comment', 'labels'],
    num_rows: 100
})

## 모델, 토크나이저 loading

- 모델 별 Model 클래스를 이용하거나 Auto class를 이용해 모델, 전처리기(tokenizer, ImageProcessor 등)을 로딩한다.
    - Huggingface에 저장된 model name을 입력해서 pretrained 모델을 loading 한다.
    - fine tuning 한 경우 모델 저장 디렉토리 경로를 넣어 pretrained 모델을 loading한다.
- AutoModel은 model name을 주면 그 모델이 학습한 base 모델에 맞는 객체를 생성해서 반환한다.
    - Auto Model은 task 별로 다양한 클래스들이 있다.
        - 클래스 이름 형식: AutoModelFor{Task형식}
        - ex) `AutoModelForObjectDetection`, `AutoModelForSequenceClassification`
    - https://huggingface.co/docs/transformers/model_doc/auto
    - 전처리기(tokenzier)는 사용하려는 모델이 사용한 전처리기를 사용해야 한다.

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_id = "beomi/kcbert-base" # 한국어 학습한 bert base model - Feature 추출
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,  # Feature Extractor
    num_labels=3   # 분류할 클래스 개수
)
# Feature Extractor: Pretrained(사전학습) 모델
# 추론기: 학습되지 않은 모델

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/619 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at beomi/kcbert-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [5]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30000, 768, padding_idx=0)
      (position_embeddings): Embedding(300, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [7]:
pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [8]:
from torchinfo import summary
summary(model)

=====================================================================================
Layer (type:depth-idx)                                       Param #
=====================================================================================
BertForSequenceClassification                                --
├─BertModel: 1-1                                             --
│    └─BertEmbeddings: 2-1                                   --
│    │    └─Embedding: 3-1                                   23,040,000
│    │    └─Embedding: 3-2                                   230,400
│    │    └─Embedding: 3-3                                   1,536
│    │    └─LayerNorm: 3-4                                   1,536
│    │    └─Dropout: 3-5                                     --
│    └─BertEncoder: 2-2                                      --
│    │    └─ModuleList: 3-6                                  85,054,464
│    └─BertPooler: 2-3                                       --
│    │    └─Linear: 3-7                                      590,592
│    │    └─Tanh: 3-8                                        --
├─Dropout: 1-2                                               --
├─Linear: 1-3                                                2,307
=====================================================================================
Total params: 108,920,835
Trainable params: 108,920,835
Non-trainable params: 0
=====================================================================================

In [ ]:
###################################################################################
# trainset/testset을 학습용으로 변환
# 현재: comment(string), labels(범주형-ClassLabel)
# 변환: 입력(comment)=>토큰화 "input_ids", "token_type_ids", "attention_mask", labels

In [ ]:
r = tokenizer("안녕하세요", return_tensors="pt")
print(r)
model(**r)

{'input_ids': tensor([[    2, 19017,  8482,     3]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.1828,  0.0844, -0.1491]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [9]:
# Dataset.map()
train_set = load_dataset_dict['train']
test_set = load_dataset_dict['test']

In [10]:
def tokenize_comment(rows):
    # batch 단위로 행들을 받아서 comment들을 tokenize해서 반환
    # rows: {"comment":[댓글, 댓글, ...], "labels":[라벨, 라벨, ...]}
    return tokenizer(rows['comment'], truncation=True) # list

trainset = train_set.map(
    tokenize_comment,
    batched=True,
    # batch_size=200, # default: 1000개
    remove_columns=['comment'] # 다 끝나고나서 지정한 컬럼들은 dataset에서 제거
)
# feature: labels, input_ids, token_type_ids, attention_mask

testset = test_set.map(
    tokenize_comment,
    batched=True,
    remove_columns=['comment']
)

trainset.set_format(type="pt")
testset.set_format(type="pt")
# 각 데이터들을 조회하면 반환할 때 지정한 타입으로 변환해서 반환.(pt: torch.tensor)

Map:   0%|          | 0/4735 [00:00<?, ? examples/s]

Map:   0%|          | 0/836 [00:00<?, ? examples/s]

In [11]:
trainset, testset

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 4735
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 836
 }))

In [12]:
trainset[0]

{'labels': tensor(1),
 'input_ids': tensor([    2,  2177,  4532,  4090,  5647,   696, 11578, 27847,  4795,    95,
             3]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])}

## 학습 (Hugging Face Transformers)

- Transformers 라이브러리는 모델 학습을 위해 `TrainingArguments`, `Trainer` 클래스를 제공한다.
- `Trainer`:
  -  데이터 로딩, 학습 루프, 평가, 로깅, 모델 저장 등을 자동으로 처리하여, 복잡한 학습 절차를 단순한 코드로 구성할 수 있도록 돕는다.
- `TrainingArguments`:
  -  `Trainer`가 사용할 **학습 관련 설정**(학습 파라미터, 로그/체크포인트 저장 방식 등)을 담당하는 클래스이다.
- 이들을 활용하면 **학습 옵션 설정, 로깅, Gradient Accumulation, Mixed Precision(AMP) 적용, 평가 및 체크포인트 관리** 등을 손쉽게 수행할 수 있다.
- `Trainer`를 사용하려면 **Datasets** 라이브러리 또는 `torch.utils.data.Dataset` 형식의 데이터셋이 필요하다.
- 일반적으로는 `Trainer`만 써도 파인튜닝을 빠르고 편리하게 할 수 있다. 하지만 학습 과정에서 특별한 계산을 해야 하거나, 일반적이지 않은 방식으로 학습을 진행해야 할 때는 `Trainer`를 쓰기 어렵다. 이럴 때는 직접 `PyTorch`로 학습 루프를 작성해 원하는 방식대로 조정한다.

In [14]:
from google.colab import userdata
hf_token = userdata.get('HF_API_KEY')

In [ ]:
from dotenv import load_dotenv
import os

load_dotenv(override=True)
hf_token = os.getenv("HUGGINGFACE_API_KEY")

In [15]:
from transformers import TrainingArguments, Trainer

# 학습된 모델을 Huggingface-hub에 올릴 때 사용할 model_id
hub_model_id = "Wjaehyun97/youtube_comment_sentiment_kcbert_finetune"

train_args = TrainingArguments(
    output_dir="saved_models", # 학습 도중 모델을 저장할 디렉토리
    # fp16=True, # weight의 타입을 float16으로 조정. 메모리가 부족할 경우 지정(float32기본)

    logging_strategy="epoch", # train loss 에폭단위로 출력

    num_train_epochs=5, # 학습 에폭 수
    per_device_train_batch_size=16, # 학습 시 batch size
    per_device_eval_batch_size=64,  # 검증/평가 시 batch size

    # gradient_accumulation_steps=4,    # 지정한 step만큼 순전파한 것을 모아서 한 번에 파라미터 업데이트
                                        # memory 문제로 batch size를 크게 할 수 없을 때 설정.
                                        # batch_size를 per_device_train_batch_size * gradient_accumulation_steps 로 지정한 효과
    # 학습 도중 모델을 평가/저장할 때 epoch/step 어떤 기준으로 할지. "epoch", "step", no
    eval_strategy="epoch",
    save_strategy="epoch",

    # 학습이 끝나고 나서 학습 도중 가장 성능이 좋았던 weight로 모델의 weight를 변경
    ## Best 모델을 제공/hf-hub에 올릴 때 True 설정
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss", # best model 선정 시 확인할 성능 지표
    greater_is_better = False, # 성능이 높은게 좋은건지 낮은게 좋은건지 설정

    # HF-hum 올리기 위한 설정 -> 학습 완료 후 자동으로 commit하기
    push_to_hub=True, # upload할 지 여부
    hub_model_id=hub_model_id, # 허브에 올릴 모델 ID
    hub_token=hf_token, # HF Access Token

    report_to="none"
)

### 평가함수 정의
- `evaluate` 패키지를 이용해 정의한다.
- `evaluate` 패키지
  - evaluate 패키지는 **모델 성능을 측정하기 위한 평가 지표(Metrics)**를 손쉽게 불러오고 사용할 수 있도록 하는 라이브러리이다.
  - 다양한 머신러닝 분야에서 사용되는 평가지표를 지원하며 필요하면 사용저 정의 평가지표를 정의할 수도 있다.

In [16]:
pip install evaluate scikit-learn

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.9 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [17]:
# 정확도 예
import evaluate
import torch

acc_fn = evaluate.load("accuracy") # 평가함수를 load
dummy_pred = torch.tensor([0, 1, 1, 0, 1])
dummy_y = torch.tensor([0, 1, 0, 0, 1])
# 평가
result = acc_fn.compute(
    predictions= dummy_pred, # 모델 에측 label
    references=dummy_y       # 정답 label
)
result

Downloading builder script: 0.00B [00:00, ?B/s]

{'accuracy': 0.8}

In [18]:
# 학습 도중/완료 후 모델을 평가할 때 사용할 함수 정의
## 기본적으로 loss는 계산을 한다. 그 이외 평가지표로 평가를 할 경우, 정의하고 Trainer에 전달.
# 만들거나 Huggingface doc에서 가져와서 사용가능

def compute_metrics(pred):
    """
    분류 문제이기에 정확도, F1 score를 평가.
    Args:
        pred(EvalPrediction) - 모델 예측값, 정답을 묶어서 제공.
    Return:
        dict - key: 평가지표이름, value: 평가점수
    """
    labels = pred.label_ids   # EvalPrediction의 정답 (ex) label-[1,2,1,0,1])

    # 모델의 출력값. [[0확률, 1확률, 2확률-logit], .] -> class값으로 변환
    preds = pred.predictions.argmax(-1)

    # 평가함수를 로딩
    acc_fn = evaluate.load("accuracy")
    f1_fn = evaluate.load("f1")

    #평가
    acc = acc_fn.compute(predictions=preds, references=labels)
    f1 = f1_fn.compute(predictions=preds, references=labels, average="weighted")

    return {"accuracy": acc, "f1-score":f1}

### Collator 함수

- **Collator(Data Collator)**는 **데이터셋에서 샘플 단위(raw examples)를 꺼낸 뒤 → 하나의 배치(batch)로 묶을 때 필요한 전처리를 수행하는 함수**이다.
- 즉, DataLoader가 `batch_size=8`로 8개의 샘플을 가져왔다면, collator는 이 8개의 샘플을 **모델이 바로 입력할 수 있는 형태**로 변환한다.
- Transformer 모델은 각 샘플의 길이가 다르므로, 이들을 자동으로 **패딩(padding)**·**마스크 생성**·**텐서 변환** 등을 해주는 장치가 필요하며, 이 역할을 담당하는 것이 **collator**이다.

#### collator가 수행하는 핵심 역할
- **정적 패딩(Static padding)/동적 패딩(Dynamic Padding)**
  - 모든 문장의 길이를 지정한 길이에 맞추기 위해 길이가 적은 경우 패딩 토큰을 추가한다.
  - 모든 학습 데이터셋의 길이를 동일하게 맞추는 것을 정적패딩, 배치 단위로 맞추는 것을 동적 패딩이라고 한다.
  - 전체 데이터셋을 미리 패딩하는 정적 패딩보다 **동적 패딩**이 메모리를 절약하고 속도를 증가시켜 더 효율적이다.

- **Attention Mask 생성**
  - 패딩된 부분은 계산에서 제외해야 한다. collator는 `attention_mask`를 자동으로 생성해 준다.

    ```bash
    Input Ids:     [101, 2003, 2023, 102, 0,   0]
    Attention Mask:[ 1,   1,   1,   1, 0,   0]
    ```

- **Label 패딩 / 정렬**

  - 텍스트 생성/요약 등에서는 target sequence도 padding 필요
  - BERT의 MLM(Masked LM)에서는 label에서 패딩에 -100을 넣는 등 규칙이 있음  (PyTorch CrossEntropyLoss는 -100을 무시)

- **텐서 변환**

    - 리스트(list) 형태의 샘플을 PyTorch/TensorFlow 텐서로 변환한다.

#### Hugging Face에서 제공하는 대표 Collator들

| Collator                             | 주 사용 모델         | 역할                      |
| ------------------------------------ | --------------- | ----------------------- |
| `DataCollatorWithPadding`            | 대부분의 모델         | 동적 패딩 처리                |
| `DataCollatorForLanguageModeling`    | BERT, RoBERTa 등 | MLM mask 생성 및 label 생성  |
| `DataCollatorForSeq2Seq`             | T5, BART 등      | 입력/출력 둘 다 패딩 및 label 정리 |
| `DataCollatorForTokenClassification` | NER 등           | token-level label 패딩    |
| `DefaultDataCollator`                | 간단한 task        | 미리 패딩된 입력만 병합           |

#### 예시

```python
from transformers import AutoTokenizer, DataCollatorWithPadding

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

collator = DataCollatorWithPadding(tokenizer=tokenizer)

# DataLoader 예시
from torch.utils.data import DataLoader

loader = DataLoader(dataset, batch_size=4, collate_fn=collator)
```

In [19]:
from transformers import DataCollatorWithPadding

# Batch 단위로 padding 처리. 가장 token 수가 많은 것에 맞춰서 padding 처리
data_collator = DataCollatorWithPadding(tokenizer=tokenizer) # max_length=10 10개에 맞춤.

# Trainer 객체 생성 -> 학습/평갈를 처리하는 객체
trainer = Trainer(
    model=model,
    args=train_args,        # TrainingArguments
    train_dataset=trainset, # 학습 데이터셋
    eval_dataset=testset,   # 검증 데이터셋
    data_collator=data_collator,
    compute_metrics=compute_metrics # 추가 평가/검증함수
)

In [20]:
# 학습(GPU 상에서 진행)
trainer.train()

Downloading builder script: 0.00B [00:00, ?B/s]

TrainOutput(global_step=1480, training_loss=0.22234620790223816, metrics={'train_runtime': 696.9379, 'train_samples_per_second': 33.97, 'train_steps_per_second': 2.124, 'total_flos': 1005646205012904.0, 'train_loss': 0.22234620790223816, 'epoch': 5.0})

In [21]:
trainer.evaluate() # eval_dataset으로 검증

{'eval_loss': 0.5587489008903503,
 'eval_accuracy': {'accuracy': 0.7691387559808612},
 'eval_f1-score': {'f1': 0.7608946993051475},
 'eval_runtime': 8.8919,
 'eval_samples_per_second': 94.018,
 'eval_steps_per_second': 1.574,
 'epoch': 5.0}

In [23]:
# 모델을 hub에 업로드 하면 반드시 **토크나이저도 같이 업로드** 한다.

from huggingface_hub import login
login(hf_token)

tokenizer.push_to_hub(hub_model_id)

# 학습 끝난 모델을 hub에 올리기
# trainer.push_to_hub(모델_id)

README.md:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/Wjaehyun97/youtube_comment_sentiment_kcbert_finetune/commit/48456aad3ed682b743081854cc3a0b7675cb0915', commit_message='Upload tokenizer', commit_description='', oid='48456aad3ed682b743081854cc3a0b7675cb0915', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Wjaehyun97/youtube_comment_sentiment_kcbert_finetune', endpoint='https://huggingface.co', repo_type='model', repo_id='Wjaehyun97/youtube_comment_sentiment_kcbert_finetune'), pr_revision=None, pr_num=None)

In [25]:
# 모델/토크나이저 로딩
load_model = AutoModelForSequenceClassification.from_pretrained(
    hub_model_id,
    device_map="auto", # 실행 컴퓨터 환경에 맞춰서 device를 설정
)
load_tokenizer = AutoTokenizer.from_pretrained(hub_model_id, device_map="auto")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

# 추론

In [30]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

txt = '너무 재밌게 봤습니다. 응원합니다.'
# 1. 토큰화
tokens = load_tokenizer(txt, return_tensors="pt")
# tokens['input_ids'].device # device(type='cpu')
# 입력 데이터들의 device를 device로 설정
tokens = {key:value.to(device) for key, value in tokens.items()}

# 2. 추론
pred = load_model(**tokens)
pred_label = pred.logits.argmax(dim=-1).item()
pred_label # 0, 긍정

0

In [31]:
trainset['labels'].features.int2str(pred_label)

'긍정'

In [32]:
# 추론함수

@torch.no_grad()
def predict(*docs):

    for doc in docs:
        tokens = load_tokenizer(doc, return_tensors="pt")
        tokens = {key:value.to(device) for key, value in tokens.items()}
        pred = load_model(**tokens)
        pred_proba = pred.logits.softmax(dim=-1) # 확률
        pred_proba = pred_proba.max(dim=-1).values.item()
        pred_label = pred.logits.argmax(dim=-1).item()

        print(f"{doc} - {trainset['labels'].features.int2str(pred_label)}, {pred_proba}")

In [33]:
predict("잠이 몰려온다.", "나는 집에 가고 싶은데...", "나는 그녀의 눈동자에 반해버렸다.", "정말 재미있어요.", "나는 그게 좀 별로였더라")

잠이 몰려온다. - 긍정, 0.9747514724731445
나는 집에 가고 싶은데... - 중립, 0.9997407793998718
나는 그녀의 눈동자에 반해버렸다. - 긍정, 0.9995157718658447
정말 재미있어요. - 긍정, 0.99982750415802
나는 그게 좀 별로였더라 - 부정, 0.9999046325683594